#!/bin/bash
#PBS -N FD
#PBS -b 1
#PBS -l elapstim_req=00:05:59             
#PBS -T mpisx  
#PBS -m abe
#PBS -M benson.muite@ut.ee
# Change to the directory that the job was submitted from
cd /sfs/fs1/ws/xhebmuit-KleinGordon/Fortran2/Fortran1DFiniteDifference6thOrder
# Launch the parallel job to the allocated compute nodes
export OMP_NUM_THREADS=1        # use 1 OMP threads
./kg
